[package]
name = "ttscli"
version = "0.1.0"
authors = ["Tom Sputz <tomsputz@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.3"
json = "0.12.0"
failure = "0.1.5"
exitfailure = "0.5.1"